### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by jciochon** [vtomole/qchackers#1]
Hi there,

I noticed this project on projectboard.xyz and was curious. I found the repo here and the website you posted. Unfortunately can't tell much about the current state of the project, but potentially interested in getting involved. I saw that the project was for a hackathon, so perhaps it has been discontinued? Any info would be great!

Cheers,
JC

**Comment by vtomole** [comment]
@jciochon The project is active. It started out as a hackathon; but I have been building on top of it for the past couple of months. I should update the website soon.
